# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb15dc6e94dc69df2a0161962025284feb5c108e40415cdb0e192fa96e9ab6db962b46848aa40738139bfc2489589ab5904236a37ea121fa9265b2bf9320403d

test:
  secret_key_base: 406cba851150a3d0d6ad9f86c1b0bf66f11f53f90afdaa7822cb6ab7ccdb3b89f663f175fcb86e70b16e47dc22e4e0443825c382fe26f06d824d467acab9c569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 96d9547b3858a3781929dc4bdf7dcd8244c8576677a044d1e2b15933d3235f2116656df49803b497cafc6c2cb1af4da3a5775b31aede94c67517f348377c686b
